config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :posts do
    resources :comments
  end

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if current_user
    @comment.save

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="content">
    <p class="comment_content"><%= comment.comment %></p>
    <p class="comment_author"><%= comment.user.email %></p>
  </div>
  <div class="buttons">
    <%= link_to "Edit", edit_post_comment_path(comment.post, comment)%>
    <%= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }%>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Reply</h1>

<%= simple_form_for([@post, @comment]) do |f| %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panda's Rails Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  </head>

  <body>
    <div class="header main_header clearfix">
      <div class="wrapper">
        <div id="logo">
          <p><%= link_to "Panda's Rails Forum", root_path %></p>
        </div>
        <div id="buttons">
          <% if user_signed_in? %>
            <%= link_to "New post", new_post_path %>
          <% else %>
            <%= link_to "sign Up", new_user_registration_path %>
            <%= link_to "sign In", new_user_session_path %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="wrapper">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div id="new_content">
  <%= simple_form_for @post do |f| %>
  <div class="new_title">
    <%= f.input :title %>
  </div>

    <%= f.input :content %>
    <%= f.submit %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form'%>

<%= link_to "Cancel", post_path %>

app/views/posts/index.html.erb
<div id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <h2 class="title"><%= link_to post.title, post %></h2>
      <p class="date">Published at <%= time_ago_in_words(post.created_at)%> ago by <%= post.user.email %></p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form'%>

app/views/posts/show.html.erb
<div id="post_content">
  <h1><%= @post.title %></h1>
  <p><%= @post.content %></p>

  <div id="comments">
    <h2><%= @post.comments.count%> Comments</h2>
    <%= render @post.comments %>

    <h3>Reply to thread </h3>
    <%= render 'comments/form'%>
  </div>

  <br>
  <hr>
  <br>
  
  <%= link_to "Edit", edit_post_path(@post), class: "button" %>
  <%= link_to "Delete", post_path(@post), method: :delete, date: {confirm: "Are you sure?"}, class: "button" %>

</div>